### ISSUE TITLE
Laravel 7.0 support?

### ISSUE THREAD

**Issue by arborrow** [stuyam/laravel-phone-validator#8]
Just checking to see if there are any plans to upgrade the dependencies for Laravel 7.0? Peace - Anthony

**Comment by liran-co** [comment]
+1

**Comment by arborrow** [comment]
I think I might ask the folks if Twilio if they might be willing to fork this project and maintain it.

**Comment by stuyam** [comment]
Happy to accept pull requests! I just haven't had the time, contributions welcome 👍

**Comment by liran-co** [comment]
Opened a PR here: https://github.com/stuyam/laravel-phone-validator/pull/9

**Comment by stuyam** [comment]
Merged & tagged 1.0.7 👍
